### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be in conflict

### ISSUE THREAD

**Issue by farinjini** [PHI-Toolkit/jupyterhub-deploy-docker-localhost#2]
Hi,

I get the following error when I run $ make notebook_image

UnsatisfiableError: The following specifications were found to be in conflict:
  - h5py 2.7*
  - r-sf -> libgdal >=2.2.2,<2.3.0a0 -> hdf5 >=1.10.2,<1.10.3.0a0
  - r-sf -> r-base >=3.4.3,<3.4.4.0a0 -> ncurses 6.0.*
Use "conda info <package>" to see the dependencies for each package.

OS: Ubuntu 16.04 Server

**Comment by hermantolentino** [comment]
Please try to use the stacks-0.2 branch and let me know how it goes. This branch installs versioned packages in the Docker container for notebook_image.
